# Generated by Django 3.2.9 on 2021-12-01 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('bank_account_no', models.PositiveIntegerField(blank=True, help_text='please leave blank it auto generated')),
                ('bank_account_balance', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='please leave blank it auto generated', max_digits=12, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Users Bank Account',
            },
        ),
        migrations.CreateModel(
            name='BankAccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=128)),
                ('account_type_image', models.ImageField(help_text='logo image for the type of account', upload_to='', verbose_name='Image Logo')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Bank Account Types',
            },
        ),
        migrations.CreateModel(
            name='WalletAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('bonus_amount_add', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bonus_amount_withdrawal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('wallet_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bonus_paid_out', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_account', to='account.bankaccount')),
            ],
            options={
                'verbose_name_plural': 'User Bonus Account',
                'ordering': ['-created'],
            },
        ),
    ]
