# Generated by Django 3.2.9 on 2021-11-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='account_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='please leave blank it auto generated', max_digits=12, null=True),
        ),
    ]
