# Generated by Django 3.2.9 on 2022-05-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccounttype',
            name='account_type_image',
            field=models.CharField(blank=True, help_text='logo image for the type of account', max_length=255, null=True, verbose_name='Image Logo'),
        ),
    ]
