# Generated by Django 3.2.9 on 2021-11-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userbankaccount_account_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['timestamp'], 'verbose_name_plural': 'Contributions'},
        ),
        migrations.RemoveField(
            model_name='userbankaccount',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='userbankaccount',
            name='gender',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
