# Generated by Django 3.2.9 on 2022-05-10 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_bankaccounttype_account_type_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccounttype',
            name='account_type_image',
        ),
    ]
