# Generated by Django 3.2.9 on 2021-11-13 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20211113_1015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonusaccount',
            options={'ordering': ['-created'], 'verbose_name_plural': 'User Bonus Account'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Contributions'},
        ),
        migrations.RemoveField(
            model_name='userbankaccount',
            name='initial_deposit',
        ),
    ]
