# Generated by Django 3.2.9 on 2021-11-13 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20211113_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbankaccount',
            name='initial_deposit_date',
        ),
        migrations.RemoveField(
            model_name='userbankaccount',
            name='interest_start_date',
        ),
    ]
