# Generated by Django 3.2.9 on 2021-11-13 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20211113_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='created_by_admin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_admin_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
