# Generated by Django 3.2.9 on 2021-11-13 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_userbankaccount_created_by_admin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonusaccount',
            name='created_by_admin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_admin_user_bonus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contribution',
            name='created_by_admin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_admin_user_target', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_by_admin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_admin_user_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='created_by_admin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_admin_user_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
