# Generated by Django 3.2.9 on 2022-04-25 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contributions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailycontribution',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='targetcontribution',
            name='account',
        ),
        migrations.AddField(
            model_name='targetcontribution',
            name='user_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account_attached', to=settings.AUTH_USER_MODEL),
        ),
    ]
