# Generated by Django 3.2.9 on 2022-04-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycontribution',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='targetcontribution',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
