# Generated by Django 3.2.9 on 2021-12-01 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contributions', '0001_initial'),
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetcontribution',
            name='created_by_admin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_admin_user_target', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='targetcontribution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_contribution_acc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailycontribution',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='account.bankaccount'),
        ),
        migrations.AddField(
            model_name='dailycontribution',
            name='created_by_admin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_admin_user_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
